### ISSUE TITLE
Make unit tests isolated

### ISSUE THREAD

**Issue by rvmelkonian** [hicommonwealth/commonwealth#2478]
## Description
Our unit tests require things to be initialized outside the scope of the unit test. This means when running individual unit tests, we get errors. We should be able to run individual unit tests the `ts-mocha` commands without any issues. 

We need to mock the data rather than instantiate `server.ts`
## *Who* is the bug affecting?
It's not a bug, but this effects Developer Productivity and leads to bad practices. 

## *What* is affected by this bug?
Tests

## *When* does this occur?
`test/integration/api/*`
Probably other tests also. 

## *Where* on the platform does it happen?
In our testing environment
 
## *How* do we replicate the issue?
Make sure you have `ts-mocha` installed globally, then inside `packages/commonwealth` Run: 
`ts-mocha -p ./tsconfig.json test/integration/api/threads.spec.ts --grep '/createThread'`
You'll see the error
```
'
Require stack:
- /Users/rvm/commonwealth/packages/commonwealth/test/integration/api/threads.spec.ts
- /Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/nodejs/esm-utils.js
- /Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/mocha.js
- /Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/cli/one-and-dones.js
- /Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/cli/options.js
- /Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/bin/mocha.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/rvm/commonwealth/packages/commonwealth/test/integration/api/threads.spec.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/ts-mocha/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/ts-mocha/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.exports.requireOrImport (/Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/nodejs/esm-utils.js:49:16)
    at Object.exports.loadFilesAsync (/Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/nodejs/esm-utils.js:91:20)
    at singleRun (/Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Users/rvm/.nvm/versions/node/v14.20.1/lib/node_modules/mocha/lib/cli/run.js:370:5)
```

## Expected behavior (i.e. solution)
Unit test should run

**Comment by CowMuon** [comment]
What was the solution here?
