### ISSUE TITLE
Unified Profiles: CA bugs

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3063]
Bugs Identified on FRACK:
- [x] Growl View Profile Redirect doesn't redirect (womp)
- [x] When Profile Image is WIDE, it isn't centered in UserComponent. 
- [x] On hover of addresses in Edit Profile Page takes too long to close, causes difficulty in saving.
- [x] Remove "Connect a new address" from Edit Profile Page (bad UX)
- [x] Add a little copy to "Manage Addresses" section (something like "You can link new addresses via the profile dropdown menu") Jessica to finalize ux copy
- [x] Show Community next addresses on Edit Profile Page (incomprehensible when too many duplicate addresses). SEE BELOW

Unrelated for launching, postponing:
- [ ] Closing "Login Modal" (prior to finishing) when connecting an address causes the success toast to appear.

<img width="939" alt="Screen Shot 2023-03-08 at 8 43 24 PM" src="https://user-images.githubusercontent.com/16248081/223893710-78501f5c-ba9e-4bfd-8506-d86dbc6e1275.png">

**Comment by CowMuon** [comment]
console error for Growl redirect: 

`Uncaught TypeError: Cannot read properties of null (reading 'profile')
    at HTMLButtonElement.onRedirectClick (app.8dbc1a88.js:77:40928)
    at C.handleEvent (932.20919788.js:2:1277542)`
