### ISSUE TITLE
Create Storybook stories for CWInput and CWButton.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3535]
## Description
- [x] Review storybook docs including [how to write stories](https://storybook.js.org/docs/react/writing-stories/introduction).
- [x] Add storybook package to devDependencies + perform [install steps](https://storybook.js.org/docs/react/get-started/install). Verify the storybook UI appears.
- [x] Write storybook stories for cw_text_input.tsx and cw_button.tsx.

## Acceptance Criteria
- Developer can run storybook UI from the Commonwealth repo and view stories for the text input and button components.

**Comment by martins87** [comment]
To run Storybook, cd into packages/commonwealth and run

`yarn

yarn storybook`

**Comment by jnaviask** [comment]
Branch name is: daniel.3535.storybook

**Comment by jnaviask** [comment]
Current state of branch: storybook builds but the page for CWButton gives:
```
ReferenceError: Buffer is not defined
    at http://localhost:6006/vendors-node_modules_ethersproject_contracts_lib_esm_index_js-node_modules_ethersproject_prov-5fd06e.iframe.bundle.js:66898:28
    at Array.forEach (<anonymous>)
    at ../../../node_modules/browserify-sign/browser/index.js (http://localhost:6006/vendors-node_modules_ethersproject_contracts_lib_esm_index_js-node_modules_ethersproject_prov-5fd06e.iframe.bundle.js:66897:25)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:320:25)
    at ../../../node_modules/crypto-browserify/index.js (http://localhost:6006/vendors-node_modules_ethersproject_contracts_lib_esm_index_js-node_modules_ethersproject_prov-5fd06e.iframe.bundle.js:93510:12)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:320:25)
    at ../../../node_modules/scryptsy/lib/scryptSync.js (http://localhost:6006/vendors-node_modules_ethersproject_contracts_lib_esm_index_js-node_modules_ethersproject_prov-5fd06e.iframe.bundle.js:191334:16)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
```

My guess is that this is because the cw_button component, through a chain of dependencies, ends up importing `models/index.ts`, which includes a LOT of different model files + pulls in many dependencies. We may want to proceed with #3467. I will try a workaround for the time being.

**Comment by jnaviask** [comment]
As for fixing webpack issues (rather than issues inside storybook with the component imports), 3 changes were sufficient to get the build working:

- Added the following line to .storybook/main.js (to omit the CSS resolver from the base webpack config):
```
        rules: [...config.module.rules, ...custom.module.rules].filter((rule) => {
          return !rule.use || !rule.use.includes('fast-sass-loader');
        }),
```
- Added the styling addon to .storybook/main.js (to build SCSS files):
```
    {
      name: '@storybook/addon-styling',
      options: {
        sass: {
          // Require your Sass preprocessor here
          implementation: require('sass'),
        },
      },
    },
```
- Added the fallbacks explicitly (for some reason the import wasn't picking them up?):
```

        fallback: {
          fs: false,
          net: false,
          zlib: require.resolve('browserify-zlib'),
          crypto: require.resolve('crypto-browserify'),
          http: require.resolve('stream-http'),
          https: require.resolve('https-browserify'),
          os: require.resolve('os-browserify/browser'),
          vm: require.resolve('vm-browserify'),
          path: require.resolve('path-browserify'),
          stream: require.resolve('stream-browserify'),
        }
```

**Comment by martins87** [comment]
> Branch name is: daniel.3535.storybook

Main branch is now `storybook.atomic-design`

I added the working stories for all components (except AvatarUpload, Content Page Card and Image Upload, all having the `Buffer is not defined` error.)

The branch is updated with master.
