### ISSUE TITLE
Ignore Datadog errors for Chain-Events-Staging

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#3697]
## Description
When the Postgres integration for Datadog was created in the main commonwealth app the scripts were not run on chain-events leading to the following error on chain-events start-up:
```
2023-05-03T20:43:05.600202+00:00 app[consumer.1]: 2023-05-03 20:43:05 UTC | CORE | WARN | (pkg/collector/python/check.go:275 in Configure) | could not get a 'postgres' check instance with the new api: Traceback (most recent call last):
2023-05-03T20:43:05.600205+00:00 app[consumer.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/postgres.py", line 67, in __init__
2023-05-03T20:43:05.600206+00:00 app[consumer.1]:     self._config = PostgresConfig(self.instance)
2023-05-03T20:43:05.600206+00:00 app[consumer.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/config.py", line 32, in __init__
2023-05-03T20:43:05.600207+00:00 app[consumer.1]:     self.port = int(self.port)
2023-05-03T20:43:05.600208+00:00 app[consumer.1]: ValueError: invalid literal for int() with base 10: '<YOUR PORT>'
2023-05-03T20:43:05.602043+00:00 app[consumer.1]: 2023-05-03 20:43:05 UTC | CORE | WARN | (pkg/collector/python/check.go:276 in Configure) | trying to instantiate the check with the old api, passing agentConfig to the constructor
2023-05-03T20:43:05.619665+00:00 app[consumer.1]: 2023-05-03 20:43:05 UTC | CORE | ERROR | (pkg/collector/python/loader.go:242 in addExpvarConfigureError) | py.loader: could not configure check 'postgres (13.4.0)': could not invoke 'postgres' python check constructor. New constructor API returned:
2023-05-03T20:43:05.619666+00:00 app[consumer.1]: Traceback (most recent call last):
2023-05-03T20:43:05.619668+00:00 app[consumer.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/postgres.py", line 67, in __init__
2023-05-03T20:43:05.619669+00:00 app[consumer.1]:     self._config = PostgresConfig(self.instance)
2023-05-03T20:43:05.619669+00:00 app[consumer.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/config.py", line 32, in __init__
2023-05-03T20:43:05.619670+00:00 app[consumer.1]:     self.port = int(self.port)
2023-05-03T20:43:05.619671+00:00 app[consumer.1]: ValueError: invalid literal for int() with base 10: '<YOUR PORT>'
2023-05-03T20:43:05.619671+00:00 app[consumer.1]: Deprecated constructor API returned:
2023-05-03T20:43:05.619672+00:00 app[consumer.1]: __init__() got an unexpected keyword argument 'agentConfig'
2023-05-03T20:43:05.620067+00:00 app[consumer.1]: 2023-05-03 20:43:05 UTC | CORE | ERROR | (pkg/collector/scheduler.go:201 in getChecks) | Unable to load a check from instance of config 'postgres': JMX Check Loader: check is not a jmx check, or unable to determine if it's so; Python Check Loader: could not configure check instance for python check postgres: could not invoke 'postgres' python check constructor. New constructor API returned:
2023-05-03T20:43:05.620068+00:00 app[consumer.1]: Traceback (most recent call last):
2023-05-03T20:43:05.620069+00:00 app[consumer.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/postgres.py", line 67, in __init__
2023-05-03T20:43:05.620069+00:00 app[consumer.1]:     self._config = PostgresConfig(self.instance)
2023-05-03T20:43:05.620069+00:00 app[consumer.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/config.py", line 32, in __init__
2023-05-03T20:43:05.620070+00:00 app[consumer.1]:     self.port = int(self.port)
2023-05-03T20:43:05.620070+00:00 app[consumer.1]: ValueError: invalid literal for int() with base 10: '<YOUR PORT>'
2023-05-03T20:43:05.620071+00:00 app[consumer.1]: Deprecated constructor API returned:
2023-05-03T20:43:05.620071+00:00 app[consumer.1]: __init__() got an unexpected keyword argument 'agentConfig'; Core Check Loader: Check postgres not found in Catalog
```

We either need to silence the errors by ignoring Postgres Datadog integration for CE or fully integrate CE databases in Datadog by running the necessary scripts and setting the proper env variables.

## Acceptance Criteria
- The error should no longer appear on dyno startup in CE and CE-staging.

**Comment by timolegros** [comment]
@jnaviask Do we want to add the chain-event databases to Datadog? It seems like the Postgres integration is quite lacking for the main CW database already so not sure if it is worth adding CE dbs.

**Comment by jnaviask** [comment]
Prob not worth adding. Cc @NakulManchanda

**Comment by NakulManchanda** [comment]
yeah, we agree not worth adding!
- root folder has `datadog`, these errors are by datadog buildpack!
- we need a way to delete or ignore this folder when deploying `chain-events`, 
- if they happen once when dynos start and we can tolerate them thats fine too!

Any suggestions @jnaviask @timolegros to customize deployment for `chain-events` to avoid seeing these errors?
