### ISSUE TITLE
For You dashboard broken for Polkadot wallet users

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4396]
## Description
The `/dashboard/for-you` page breaks with the following error on production for users that sign in with the Polkadot wallet extension.
```
TypeError: Cannot read properties of undefined (reading 'address')
    at 2294.c4688fc5.chunk.js:1:3786
    at Array.map (<anonymous>)
    at g (2294.c4688fc5.chunk.js:1:3496)
    at Sa (5710.a3a91ca6.js:1:2364484)
    at xu (5710.a3a91ca6.js:1:2421443)
    at bl (5710.a3a91ca6.js:1:2410425)
    at vl (5710.a3a91ca6.js:1:2410353)
    at gl (5710.a3a91ca6.js:1:2410216)
    at ol (5710.a3a91ca6.js:1:2407023)
    at il (5710.a3a91ca6.js:1:2405578)
```

The error on local master is more descriptive:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'address')
    at eval (cw_avatar_group.tsx:40:1)
    at Array.map (<anonymous>)
    at CWAvatarGroup (cw_avatar_group.tsx:23:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
```

To recreate you literally just have to log in with Polkadot on `https://commonwealth.im/` and the for you landing page will break. This was tested with both an existing Polkadot account and a new account/address that is not linked to the existing one.

## Engineering Requirements

- No reading of `address` from undefined.

## Acceptance Criteria

- Should be able to view the for-you dashboard after logging in with the Polkadot wallet extension.

**Comment by jnaviask** [comment]
Potentially related to #4401

**Comment by timolegros** [comment]
> Potentially related to #4401

Confirmed unrelated. The join error is gone with the various import fixes but the dashboard issue persists.

**Comment by timolegros** [comment]
No longer reproducible.
