### ISSUE TITLE
Celo Web3-Provider error

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4445]
## Description
Celo chains throw an error when using `Web3-providers-http` locally.
```
Error: invalid argument 0: hex number with leading zero digits
    at /home/timolegros/Projects/commonwealth/node_modules/@ethersproject/providers/src.ts/web3-provider.ts:71:35
    at /home/timolegros/Projects/commonwealth/node_modules/web3-providers-http/lib/index.js:138:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[ERROR] 15:03:15 Error: invalid argument 0: hex number with leading zero digits
```

This issue is potentially related to #4272. Subscriber 2 and 3 are both running out of memory and both of these subscribers listen to Celo (subscriber 1 does not listen to any Celo based contract). That said, this error is not being logged in production. Either, the error is not occurring or it is occurring silently and the retry mechanism of the listeners is leading to a pileup of connections.

## Engineering Requirements

- No error for Celo chains locally.

**Comment by timolegros** [comment]
The Ethereum [JSON-RPC API Specification][1] actually states the following:
![Screenshot from 2023-07-10 16-36-09](https://github.com/hicommonwealth/commonwealth/assets/62490329/e2b468fe-1743-4db2-9e77-424e0cf39f24)

Thus leading zeros are actually a mistake for all of our EVM requests. Unfortunately, the given `ethers.utils.hexStripZeros` function converts `0x0` (which is 0 in base 10) to `0x` which would be invalid. Thus the solution for this issue is a small custom function which converts decimals to big numbers and then to hexadecimal with no leading zeros while preserving actual zero. 

Thanks @ianrowan for the link.

[1]: https://ethereum.org/en/developers/docs/apis/json-rpc/
