### ISSUE TITLE
Investigate CI/CD errors for integration and api errors

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#5425]
## Describe the bug

ENV: CI/CD
Branch: Master

When CI/CD executes tests we have green checkmark, if we investigate log's we will see that some errors throw 500 errors for api. We need to investigate those errors. 

## To Reproduce

1. Execute integration and api tests on local
2. Check logs
## Expected behavior

Logs should not have 500 errors.

## Additional context

Some errors from run:
https://github.com/hicommonwealth/commonwealth/actions/runs/6614393425/job/17964277105

Here is some logs
```
2023-10-23 14:08:16,435 INFO [server-test.ts] /cachedummy/broken5xx called
Trace: ServerError: broken route
    at /home/runner/work/commonwealth/commonwealth/packages/commonwealth/server-test.ts:186:19
    at newFn (/home/runner/work/commonwealth/commonwealth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/route.js:144:13)
    at CacheDecorator.cache (/home/runner/work/commonwealth/commonwealth/packages/common-common/src/cacheDecorator.ts:269:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 500,
  error: Error: route error
      at /home/runner/work/commonwealth/commonwealth/packages/commonwealth/server-test.ts:185:19
      at newFn (/home/runner/work/commonwealth/commonwealth/node_modules/express-async-errors/index.js:16:20)
      at Layer.handle [as handle_request] (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/layer.js:95:5)
      at next (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/route.js:144:13)
      at CacheDecorator.cache (/home/runner/work/commonwealth/commonwealth/packages/common-common/src/cacheDecorator.ts:269:16)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
}
    at /home/runner/work/commonwealth/commonwealth/packages/common-common/src/scripts/setupErrorHandlers.ts:23:15
    at newFn (/home/runner/work/commonwealth/commonwealth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:326:13)
    at /home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:[34](https://github.com/hicommonwealth/commonwealth/actions/runs/6614393425/job/17964277105#step:10:35)6:12)
    at next (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle_error (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:326:13)
    at /home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:346:12)
    at next (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/index.js:280:10)
    at next (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/route.js:1[36](https://github.com/hicommonwealth/commonwealth/actions/runs/6614393425/job/17964277105#step:10:37):14)
    at /home/runner/work/commonwealth/commonwealth/packages/commonwealth/server-test.ts:186:14
    at newFn (/home/runner/work/commonwealth/commonwealth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/work/commonwealth/commonwealth/node_modules/express/lib/router/route.js:144:13)
    at CacheDecorator.cache (/home/runner/work/commonwealth/commonwealth/packages/common-common/src/cacheDecorator.ts:269:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-23 14:08:16,[44](https://github.com/hicommonwealth/commonwealth/actions/runs/6614393425/job/17964277105#step:10:45)4 WARN [cacheDecorator.ts] NOSET: /cachedummy/broken5xx Response status code is not 200 but 500, skip writing cache
2023-10-23 14:08:16,[46](https://github.com/hicommonwealth/commonwealth/actions/runs/6614393425/job/17964277105#step:10:47)0 INFO [server-test.ts] /cachedummy/broken5xx called
```

```
original: error: column "nan" does not exist
      at Parser.parseErrorMessage (/home/runner/work/commonwealth/commonwealth/node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (/home/runner/work/commonwealth/commonwealth/node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (/home/runner/work/commonwealth/commonwealth/node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (/home/runner/work/commonwealth/commonwealth/node_modules/pg-protocol/src/index.ts:7:48)
      at Socket.emit (node:events:517:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:335:12)
      at readableAddChunk (node:internal/streams/readable:308:9)
      at Socket.Readable.push (node:internal/streams/readable:245:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 104,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '521',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3713',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "address_id", "created_by", "title", "body", "plaintext", "kind", "stage", "url", "topic_id", "pinned", "chain", "view_count", "read_only", "version_history", "links", "discord_meta", "has_poll", "canvas_action", "canvas_session", "canvas_hash", "created_at", "updated_at", "last_edited", "deleted_at", "last_commented_on", "marked_as_spam_at", "archived_at", "locked_at", "reaction_count", "comment_count", "max_notif_id" FROM "Threads" AS "Thread" WHERE ("Thread"."deleted_at" IS NULL AND "Thread"."id" = NaN);',
    parameters: undefined
  },
  sql: 'SELECT "id", "address_id", "created_by", "title", "body", "plaintext", "kind", "stage", "url", "topic_id", "pinned", "chain", "view_count", "read_only", "version_history", "links", "discord_meta", "has_poll", "canvas_action", "canvas_session", "canvas_hash", "created_at", "updated_at", "last_edited", "deleted_at", "last_commented_on", "marked_as_spam_at", "archived_at", "locked_at", "reaction_count", "comment_count", "max_notif_id" FROM "Threads" AS "Thread" WHERE ("Thread"."deleted_at" IS NULL AND "Thread"."id" = NaN);',
  parameters: {}
}
```

**Comment by kurtisassad** [comment]
First error we expect it in the test itself. Notice that the route is called
`/cachedummy/broken5xx` Its purpose is to check some caching functionality related to returning a 500 error.
