### ISSUE TITLE
QA (unclear whether this still happens) identityFetchCache produces an error when updating a profile for the first time

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#580]
- Run yarn reset-server
- Link a new address
- When setting its profile, the first time saving its profile, an error will occur:

```
2020-08-05 17:17:03,587 ERROR [setupErrorHandlers.ts] TypeError: Cannot read property 'edgeware' of undefined
    at IdentityFetchCache.<anonymous> (/Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:32:23)
    at Generator.next (<anonymous>)
    at /Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:4:12)
    at IdentityFetchCache.add (/Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:34:16)
    at /Users/raymond/Development/commonwealth/server/routes/updateProfile.ts:94:32
    at Generator.next (<anonymous>)
    at fulfilled (/Users/raymond/Development/commonwealth/server/routes/updateProfile.ts:5:58)
POST /api/updateProfile 500 30.309 ms - 56
```

**Comment by jnaviask** [comment]
> When setting its profile, the first time saving its profile, an error will occur

How do I do this step? I don't see a modal or form or anything.

**Comment by raykyri** [comment]
We skip the Update Profile if you are logging in with a pre-existing address, but you should be able to see if if you either 1) log in with an address that hasn't been used before, or 2) are already logged in, and link a different address.

**Comment by jnaviask** [comment]
I tried these and didn't get dialogs, at least when I tried to replicate last.
