### ISSUE TITLE
Fix Stake imports to use new @hicommonwealth libs pattern

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#6555]
Broken in initial v0.9.4 cut:
```
2024-02-02T16:21:04.033520+00:00 app[web.1]: Unhandled Rejection Error: Cannot find module '@hicommonwealth/chains/src/commonProtocol/utils'
2024-02-02T16:21:04.033559+00:00 app[web.1]: Require stack:
2024-02-02T16:21:04.033560+00:00 app[web.1]: - /app/packages/commonwealth/build/server/controllers/server_comments_methods/create_comment_reaction.js
2024-02-02T16:21:04.033560+00:00 app[web.1]: - /app/packages/commonwealth/build/server/controllers/server_comments_controller.js
2024-02-02T16:21:04.033561+00:00 app[web.1]: - /app/packages/commonwealth/build/server/routing/router.js
2024-02-02T16:21:04.033562+00:00 app[web.1]: - /app/packages/commonwealth/build/main.js
2024-02-02T16:21:04.033562+00:00 app[web.1]: - /app/packages/commonwealth/build/server.js
2024-02-02T16:21:04.033563+00:00 app[web.1]: at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
2024-02-02T16:21:04.033563+00:00 app[web.1]: at Module._load (node:internal/modules/cjs/loader:975:27)
2024-02-02T16:21:04.033563+00:00 app[web.1]: at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-02-02T16:21:04.033564+00:00 app[web.1]: at require (node:internal/modules/helpers:177:18)
2024-02-02T16:21:04.033566+00:00 app[web.1]: at Object.<anonymous> (/app/packages/commonwealth/server/controllers/server_comments_methods/create_comment_reaction.ts:2:1)
2024-02-02T16:21:04.033566+00:00 app[web.1]: at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-02-02T16:21:04.033566+00:00 app[web.1]: at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-02-02T16:21:04.033567+00:00 app[web.1]: at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-02-02T16:21:04.033567+00:00 app[web.1]: at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-02-02T16:21:04.033567+00:00 app[web.1]: at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-02-02T16:21:04.033567+00:00 app[web.1]: at require (node:internal/modules/helpers:177:18)
2024-02-02T16:21:04.033568+00:00 app[web.1]: at Object.<anonymous> (/app/packages/commonwealth/server/controllers/server_comments_controller.ts:7:1)
2024-02-02T16:21:04.033568+00:00 app[web.1]: at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-02-02T16:21:04.033569+00:00 app[web.1]: at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-02-02T16:21:04.033569+00:00 app[web.1]: at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-02-02T16:21:04.033569+00:00 app[web.1]: at Module._load (node:internal/modules/cjs/loader:1013:12) {
2024-02-02T16:21:04.033569+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2024-02-02T16:21:04.033570+00:00 app[web.1]: requireStack: [
2024-02-02T16:21:04.033570+00:00 app[web.1]: '/app/packages/commonwealth/build/server/controllers/server_comments_methods/create_comment_reaction.js',
2024-02-02T16:21:04.033571+00:00 app[web.1]: '/app/packages/commonwealth/build/server/controllers/server_comments_controller.js',
2024-02-02T16:21:04.033571+00:00 app[web.1]: '/app/packages/commonwealth/build/server/routing/router.js',
2024-02-02T16:21:04.033571+00:00 app[web.1]: '/app/packages/commonwealth/build/main.js',
2024-02-02T16:21:04.033571+00:00 app[web.1]: '/app/packages/commonwealth/build/server.js'
2024-02-02T16:21:04.033571+00:00 app[web.1]: ]
2024-02-02T16:21:04.033572+00:00 app[web.1]: }
```

**Comment by jnaviask** [comment]
Closed by #6554
