### ISSUE TITLE
After resetting server, creating a new account using wallet sign-in results in an error on the first try

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#678]
This was reported earlier but it didn't replicate consistently on either my or Jake's computer. But now it seems to replicate a little more consistently and seems worth another look:

```
2020-08-27 17:10:11,023 ERROR [setupErrorHandlers.ts] TypeError: Cannot read property 'kulupu' of undefined
    at IdentityFetchCache.<anonymous> (/Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:32:23)
    at Generator.next (<anonymous>)
    at /Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:4:12)
    at IdentityFetchCache.add (/Users/raymond/Development/commonwealth/server/util/identityFetchCache.ts:34:16)
    at /Users/raymond/Development/commonwealth/server/routes/updateProfile.ts:94:32
    at Generator.next (<anonymous>)
    at fulfilled (/Users/raymond/Development/commonwealth/server/routes/updateProfile.ts:5:58)
```

This error occurs when creating an OffchainProfile as part of the login flow. Trying to make the request again (by saving the profile again) works however.

**Comment by jnaviask** [comment]
Observed this earlier today and fixed it in commit 4f647e67a78263826c8facb1e34a8d1524118570.
