### ISSUE TITLE
BUG: Log out is broken

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7861]
## Describe the bug

On current master if user tries to log out from platform we have 500 error
### Initial conditions

**Environment:** 

Local
**Branch/Release version:** 

Master
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Sign up on application
2. Click on log out

## Actual behavior

We have 500 error in console

## Expected behavior

Log out should work

## Additional context

```
[16:40:17.925] ERROR (setupErrorHandlers.ts): req#logout requires a callback function {"url":"/api/logout","method":"GET","headers":{"host":"localhost:9000","referer":"http://localhost:9000/osmosis/discussion/17161-ilija-testira-local"},"user":{},"status":500}
    err: {
      "type": "Error",
      "message": "req#logout requires a callback function",
      "stack":
          Error: req#logout requires a callback function
              at req.logout.req.logOut (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/passport/lib/http/request.js:65:44)
              at logout (/Users/ilijabojanovic/Documents/work/common/commonwealth/packages/commonwealth/server/routes/logout.ts:10:7)
              at newFn (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/express-async-errors/index.js:16:20)
              at Layer.handle [as handle_request] (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/express/lib/router/layer.js:95:5)
              at next (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/express/lib/router/route.js:144:13)
              at <anonymous> (/Users/ilijabojanovic/Documents/work/common/commonwealth/packages/commonwealth/server/middleware/methodNotAllowed.ts:33:3)
              at newFn (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/express-async-errors/index.js:16:20)
              at Layer.handle [as handle_request] (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/express/lib/router/layer.js:95:5)
              at next (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/express/lib/router/route.js:144:13)
              at Route.dispatch (/Users/ilijabojanovic/Documents/work/common/commonwealth/node_modules/express/lib/router/route.js:114:3)
    }
[14:40:17.945] GET /api/logout 500 37ms
[14:40:17.987] POST /api/getAddressProfile 200 20ms
```

**Comment by kurtisassad** [comment]
Seems that #7861 fixed this issue. More specifically this change:

https://github.com/hicommonwealth/commonwealth/pull/7798/files#diff-e3c48cecc97fc796153b19200aa518b1d97f3cb33e3e1756c1e5e4411e858cee

I guess we can either include this PR in the release or cherry pick a small change onto the release? Any preferences @ilijabojanovic @jnaviask

**Comment by jnaviask** [comment]
@kurtisassad I'm going to bump the state of v1.4.0 now to include this PR.
