### ISSUE TITLE
Contest winner is not getting paid

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#8061]
### Initial conditions

**Environment:** 

**Branch/Release version:** 

ryan/contest-bug-fixes-v2
**Browser:** 

**Wallet:** 

## Reproduction steps

- as an admin create one off contest with some topic included
- fund contest with some eth 
- as a user create a thread within contest
- using one or more accounts, upvote created thread
- wait up to 5 minutes until the contest is finished

## Actual behavior

- contest is finished but the prize is not sent to the winner
 
## Expected behavior

- after finished contest, the prize should be sent to the address of the author of winning thread
 
## Reporter

@masvelio 
## Additional context

- address that should be paid https://sepolia.basescan.org/address/0x725D899B56630780344F00146E1B29aBEf6D6303
- contest contract https://sepolia.basescan.org/address/0x82b8099c7a671f22e85c1ab1c2cdfa7377d9af6c
- one of the error from consumer 
```
[15:26:57.352] ERROR (RabbitMQAdapter.ts): Failed to process event {"topic":"ContestWorkerPolicy","message":{"name":"ThreadUpvoted","payload":{"id":126557,"reaction":"like","thread_id":16675,"address_id":174395,"comment_id":null,"created_at":"2024-06-05T13:26:35.225Z","updated_at":"2024-06-05T13:26:35.225Z","canvas_hash":"0x870237f056d2cf23db960b47826e47de39624b8618a41363ff78d74cfc964859","proposal_id":null,"community_id":"05062024-1423","canvas_action":"{\"type\":\"action\",\"payload\":{\"app\":\"/commonwealth\",\"from\":\"0x067a7910789f214A13E195a025F881E9B59C4D76\",\"timestamp\":1717593994909,\"chain\":\"eip155:84532\",\"block\":\"0x1a25a355610234f8d83474d3b1b39dc20e0d92605366df4bb38a72c4ab60a9fd\",\"call\":\"reactThread\",\"callArgs\":{\"thread_id\":16675,\"value\":\"like\"}},\"session\":\"0x715A2dAC707146583Ae967d2da7066219d9c7D67\",\"signature\":\"0x60546cc602ecc18cdd0bb4d911050830818a92765e8d3c6dd8ff51127a5dd1dc3613dbf1c37e8ef421b2dbc319a43492e05f2715d5f0d248fe363897cf0be7bd1c\"}","canvas_session":"{\"type\":\"session\",\"payload\":{\"app\":\"/commonwealth\",\"block\":\"0x1a25a355610234f8d83474d3b1b39dc20e0d92605366df4bb38a72c4ab60a9fd\",\"chain\":\"eip155:84532\",\"from\":\"0x067a7910789f214A13E195a025F881E9B59C4D76\",\"sessionAddress\":\"0x715A2dAC707146583Ae967d2da7066219d9c7D67\",\"sessionDuration\":86400000,\"sessionIssued\":1717509722548},\"signature\":\"http://localhost:8081/wqQ3N8mLO2STdoukv/0xd122649a6dbc83dbbc85903da472c9894019c204e1f5e81c5856e898f719a9c24be6015a3c3d7130dbd13e0d6691baee5637742d6d8b8a462899fc4005ab74d51b\"}","calculated_voting_weight":1}}}
    err: {
      "type": "Error",
      "message": "voteContent failed 1 times: AppError: Failed to push content to chain: TransactionRevertedWithoutReasonError: Transaction has been reverted by the EVM:\n {\"blockHash\":\"0xd52be9ccd762c5b1dbc91f8efc7e2a6a8041976294ba894d0df32a3daa130b4a\",\"blockNumber\":\"10912864\",\"cumulativeGasUsed\":\"72500\",\"effectiveGasPrice\":\"2592777384\",\"from\":\"0x067a7910789f214a13e195a025f881e9b59c4d76\",\"gasUsed\":\"28661\",\"logs\":[],\"logsBloom\":\"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"status\":\"0\",\"to\":\"0x82b8099c7a671f22e85c1ab1c2cdfa7377d9af6c\",\"transactionHash\":\"0xd3c16553e6fce8cde1a4de9ba5408e953a8ca1935ac6277ae91c8e82977f1b84\",\"transactionIndex\":\"1\",\"type\":\"2\"}\"",
      "stack":
          Error: voteContent failed 1 times: AppError: Failed to push content to chain: TransactionRevertedWithoutReasonError: Transaction has been reverted by the EVM:
           {"blockHash":"0xd52be9ccd762c5b1dbc91f8efc7e2a6a8041976294ba894d0df32a3daa130b4a","blockNumber":"10912864","cumulativeGasUsed":"72500","effectiveGasPrice":"2592777384","from":"0x067a7910789f214a13e195a025f881e9b59c4d76","gasUsed":"28661","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0","to":"0x82b8099c7a671f22e85c1ab1c2cdfa7377d9af6c","transactionHash":"0xd3c16553e6fce8cde1a4de9ba5408e953a8ca1935ac6277ae91c8e82977f1b84","transactionIndex":"1","type":"2"}"
              at Object.ThreadUpvoted (/Users/marcin/Desktop/Projects/commonwealth/libs/model/src/policies/ContestWorker.policy.ts:220:17)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at handleEvent (/Users/marcin/Desktop/Projects/commonwealth/libs/core/src/framework/event.ts:34:8)
    }

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by ianrowan** [comment]
Payout does not automatically occur at the time the contest ends, but rather at the time of the first transaction after the contest has ended. 

Here, the first/next attempted action is the vote action which is failing with the following error:

<img width="586" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/370b2489-f0cb-4221-a239-b3379577fec7">

This implies that the content id being voted on does not exist on this specific contest.

And upon further investigation on etherscan - it appears contentId 0 was added and voted on. Then 4 votes were attempted on content id 1 which has not record on chain of being created 

If content 1 was added to chain, this contest should payout as expected and votes should succeed. 

I think the main investigation would be re: how a vote for content 1 is being routed on the platform/how content 1 may not have been sequenced on chain

CC @ryanbennettvoid @masvelio

**Comment by masvelio** [comment]
after further testing, it turned out that some recent platform bugs were causing the cascade of the issues and one of them was preventing payouts. We looked at it again with @ianrowan and @rbennettcw and it looks like payouts work fine, especially after [this PR](https://github.com/hicommonwealth/commonwealth/pull/8138), which starts new recurring contest automatically AND automatically sends payout to the winner.  

in etherscan, payouts are visible in internal transactions tab, eg
https://sepolia.basescan.org/address/0x067a7910789f214a13e195a025f881e9b59c4d76#internaltx
