### ISSUE TITLE
If something goes wrong during the creation of the contest, contest with wrong data is created

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#8108]
## Describe the bug

If something goes wrong during the creation of the contest, the default values that are used for creating contest have wrong types. As a result, backend throws 500 to the frontend. 
### Initial conditions

**Environment:** 

**Branch/Release version:** 

master
**Browser:** 

**Wallet:** 

## Reproduction steps

- I am not sure how exactly reproduce this issue, but happened to me couple times. [This code](https://github.com/hicommonwealth/commonwealth/blob/74f5c50a1bcb683ff0178fab355a443d9d68fb78/libs/model/src/contest/Contests.projection.ts#L91) should be modified to create data that is aligned with the output type

## Screenshots / Video

```
"0x7FE6FF3f5e23F0191b6eD34F99311C9094dd0eC1"	"base111118"	300	"2024-06-10 14:21:57.37+02"	"base111118"	"http://default.image"			{}		"ETH"	18
```
<img width="1586" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/310e66ee-0219-4704-8ac9-bafd665f2a95">

```
[14:22:22.875] ERROR (index.ts): INTERNAL_SERVER_ERROR: [ZodError] contest.getAllContests: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      1,
      "funding_token_address"
    ],
    "message": "Expected string, received null"
  },
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "null",
    "path": [
      1,
      "prize_percentage"
    ],
    "message": "Expected number, received null"
  },
  {
    "code": "invalid_type",
    "expected": "boolean",
    "received": "null",
    "path": [
      1,
      "cancelled"
    ],
    "message": "Expected boolean, received null"
  }
] 
    err: {
      "type": "ZodError",
      "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      1,\n      \"funding_token_address\"\n    ],\n    \"message\": \"Expected string, received null\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"number\",\n    \"received\": \"null\",\n    \"path\": [\n      1,\n      \"prize_percentage\"\n    ],\n    \"message\": \"Expected number, received null\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"boolean\",\n    \"received\": \"null\",\n    \"path\": [\n      1,\n      \"cancelled\"\n    ],\n    \"message\": \"Expected boolean, received null\"\n  }\n]",
      "stack":
          ZodError: [
            {
              "code": "invalid_type",
              "expected": "string",
              "received": "null",
              "path": [
                1,
                "funding_token_address"
              ],
              "message": "Expected string, received null"
            },
            {
              "code": "invalid_type",
              "expected": "number",
              "received": "null",
              "path": [
                1,
                "prize_percentage"
              ],
              "message": "Expected number, received null"
            },
            {
              "code": "invalid_type",
              "expected": "boolean",
              "received": "null",
              "path": [
                1,
                "cancelled"
              ],
              "message": "Expected boolean, received null"
            }
          ]
              at get error [as error] (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/zod@3.23.6/node_modules/zod/lib/index.mjs:587:31)
              at ZodArray.parseAsync (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/zod@3.23.6/node_modules/zod/lib/index.mjs:715:22)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async outputMiddleware (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:308:26)
              at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
              at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
              at async resolve (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
              at async inputToProcedureCall (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
              at async Promise.all (index 0)
              at async resolveHTTPResponse (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:182:37)
      "aggregateErrors": [
        {
          "type": "Object",
          "message": "Expected string, received null",
          "stack":
              
          "code": "invalid_type",
          "expected": "string",
          "received": "null",
          "path": [
            1,
            "funding_token_address"
          ]
        },
        {
          "type": "Object",
          "message": "Expected number, received null",
          "stack":
              
          "code": "invalid_type",
          "expected": "number",
          "received": "null",
          "path": [
            1,
            "prize_percentage"
          ]
        },
        {
          "type": "Object",
          "message": "Expected boolean, received null",
          "stack":
              
          "code": "invalid_type",
          "expected": "boolean",
          "received": "null",
          "path": [
            1,
            "cancelled"
          ]
        }
      ],
      "issues": [
        {
          "code": "invalid_type",
          "expected": "string",
          "received": "null",
          "path": [
            1,
            "funding_token_address"
          ],
          "message": "Expected string, received null"
        },
        {
          "code": "invalid_type",
          "expected": "number",
          "received": "null",
          "path": [
            1,
            "prize_percentage"
          ],
          "message": "Expected number, received null"
        },
        {
          "code": "invalid_type",
          "expected": "boolean",
          "received": "null",
          "path": [
            1,
            "cancelled"
          ],
          "message": "Expected boolean, received null"
        }
      ],
      "name": "ZodError"
    }
```

## Reporter

@masvelio

**Comment by rbennettcw** [comment]
1. In general, it's okay if the ContestManager doesn't get created via the API. Within a few seconds, the onchain event will upsert the ContestManager from onchain data and make it correct.

2. To fix, we need exact steps to repro, because the result depends on what the UI sends. Rather than modifying code to repro, we need to know what real-life steps result in the bug.
