### ISSUE TITLE
Fix failing user model test

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#827]
```
  1) User Model Routes
       /updateEmail
         should fail to update if email in use by another user:
     AssertionError: expected undefined to equal 'Email already in use'
      at /Users/raymond/Development/commonwealth/test/unit/api/user.spec.ts:77:36
      at Generator.next (<anonymous>)
      at fulfilled (test/unit/api/user.spec.ts:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by zakhap** [comment]
I ended up just fixing this in my pr as I was fixing other tests.
