### ISSUE TITLE
My Stake Transaction page does not work

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#8382]
### Initial conditions

**Environment:** 

**Branch/Release version:** 
master

**Browser:** 

**Wallet:** 

## Reproduction steps

1. buy stake
2. go to my transaction page
## Actual behavior

3. trpc error in the console
4. page says that you didnt buy any stake
## Expected behavior

3. should show list of transaction
## Screenshots / Video

https://github.com/hicommonwealth/commonwealth/assets/14819225/63b3a22c-4353-4b91-ad50-e29b4cf70bf0

## Reporter

@masvelio

**Comment by kurtisassad** [comment]
I can't seem to reproduce, tried with base sepolia. Transaction page works fine. I would be curious to what your response reads for the getStakeTransaction if you expand it

**Comment by masvelio** [comment]
FE
```
[
    {
        "error": {
            "message": "Output validation failed",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "stack": "TRPCError: Output validation failed\n    at outputMiddleware (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:314:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)\n    at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)\n    at async resolve (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)\n    at async inputToProcedureCall (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)\n    at async Promise.all (index 0)\n    at async resolveHTTPResponse (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:182:37)\n    at async file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-97af83bc.mjs:67:9\n    at async file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/adapters/express.mjs:17:9",
                "path": "community.getStakeTransaction"
            }
        }
    }
]
```

BE
```
[18:44:17.201] ERROR (index.ts): INTERNAL_SERVER_ERROR: [ZodError] community.getStakeTransaction: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      4,
      "community",
      "icon_url"
    ],
    "message": "Expected string, received null"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      43,
      "community",
      "icon_url"
    ],
    "message": "Expected string, received null"
  }
] 
    err: {
      "type": "ZodError",
      "message": "[\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      4,\n      \"community\",\n      \"icon_url\"\n    ],\n    \"message\": \"Expected string, received null\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"null\",\n    \"path\": [\n      43,\n      \"community\",\n      \"icon_url\"\n    ],\n    \"message\": \"Expected string, received null\"\n  }\n]",
      "stack":
          ZodError: [
            {
              "code": "invalid_type",
              "expected": "string",
              "received": "null",
              "path": [
                4,
                "community",
                "icon_url"
              ],
              "message": "Expected string, received null"
            },
            {
              "code": "invalid_type",
              "expected": "string",
              "received": "null",
              "path": [
                43,
                "community",
                "icon_url"
              ],
              "message": "Expected string, received null"
            }
          ]
              at get error [as error] (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/zod@3.23.6/node_modules/zod/lib/index.mjs:587:31)
              at ZodArray.parseAsync (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/zod@3.23.6/node_modules/zod/lib/index.mjs:715:22)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async outputMiddleware (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:308:26)
              at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
              at async callRecursive (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
              at async resolve (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:481:24)
              at async inputToProcedureCall (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:46:22)
              at async Promise.all (index 0)
              at async resolveHTTPResponse (file:///Users/marcin/Desktop/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/resolveHTTPResponse-2fc435bb.mjs:182:37)
      "aggregateErrors": [
        {
          "type": "Object",
          "message": "Expected string, received null",
          "stack":
              
          "code": "invalid_type",
          "expected": "string",
          "received": "null",
          "path": [
            4,
            "community",
            "icon_url"
          ]
        },
        {
          "type": "Object",
          "message": "Expected string, received null",
          "stack":
              
          "code": "invalid_type",
          "expected": "string",
          "received": "null",
          "path": [
            43,
            "community",
            "icon_url"
          ]
        }
      ],
      "issues": [
        {
          "code": "invalid_type",
          "expected": "string",
          "received": "null",
          "path": [
            4,
            "community",
            "icon_url"
          ],
          "message": "Expected string, received null"
        },
        {
          "code": "invalid_type",
          "expected": "string",
          "received": "null",
          "path": [
            43,
            "community",
            "icon_url"
          ],
          "message": "Expected string, received null"
        }
      ],
      "name": "ZodError"
    }
```

**Comment by masvelio** [comment]
btw thats not great that we are getting 500 error if there is a schema validation error. Does this work like that on the production as well?

**Comment by kurtisassad** [comment]
Super helpful, thanks! Putting the fix up in a few secs
