### ISSUE TITLE
Cosmos join community with existing account broken

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#9362]
## Description
Can't join a Cosmos community e.g. kyve with a Keplr wallet:
![image](https://github.com/user-attachments/assets/78f3491f-00cd-4607-9a24-ad18c7672806)

```
[10:20:30.369] ERROR (utils.ts): INTERNAL_SERVER_ERROR: [ServerError] community.joinCommunity: Address failed assertion check {"fingerprint":"INTERNAL_SERVER_ERROR-ServerError-community.joinCommunity"}
    err: {
      "type": "ServerError",
      "message": "Address failed assertion check",
      "stack":
          ServerError: Address failed assertion check
              at assertAddressOwnership (/home/timolegros/Projects/commonwealth/libs/model/src/utils/denormalizedCountUtils.ts:67:13)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at body (/home/timolegros/Projects/commonwealth/libs/model/src/community/JoinCommunity.command.ts:64:7)
              at command (/home/timolegros/Projects/commonwealth/libs/core/src/framework/command.ts:32:13)
              at <anonymous> (/home/timolegros/Projects/commonwealth/libs/adapters/src/trpc/handlers.ts:65:16)
              at async resolveMiddleware (file:///home/timolegros/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:421:30)
              at async callRecursive (file:///home/timolegros/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
              at async outputMiddleware (file:///home/timolegros/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:302:24)
              at async callRecursive (file:///home/timolegros/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
              at async callRecursive (file:///home/timolegros/Projects/commonwealth/node_modules/.pnpm/@trpc+server@10.45.2/node_modules/@trpc/server/dist/index.mjs:451:32)
      "status": 500,
      "name": "ServerError"
    }

```

**Comment by timolegros** [comment]
Seems to be resolved on latest master + in JoinCommunity.command PR.
