### ISSUE TITLE
Can't login "No Wallets Founder"

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#9603]
## Describe the bug
I've got metamask installed and it says connected to the site.
<img width="358" alt="image" src="https://github.com/user-attachments/assets/b193d2bc-77b1-4a9b-9067-69e710630166">

Yet it doesn't allow me to login at all.
<img width="673" alt="image" src="https://github.com/user-attachments/assets/3466bfec-716c-411b-bd73-456897fe7ce4">

### Initial conditions
Google chrome

## Reproduction steps
IDK

**Comment by drewstone** [comment]
Can't even login with Github, was this removed?

**Comment by drewstone** [comment]
Console errors
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at Me (https://commonwealth.im/assets/index-DSouKFnJ.js:1578:9332)
    at div
    at div
    at yt (https://commonwealth.im/assets/ThreadOptions-DofEkh0p.js:1:6657)
    at div
    at It (https://commonwealth.im/assets/ThreadOptions-DofEkh0p.js:3:38)
    at div
    at div
    at a
    at Me (https://commonwealth.im/assets/index-DSouKFnJ.js:1578:9332)
    at hs (https://commonwealth.im/assets/ThreadCard-D03e54OI.js:1:1019)
    at div
    at div
    at https://commonwealth.im/assets/index-BHaJreJ3.js:1:34698
    at div
    at Zo (https://commonwealth.im/assets/index-BHaJreJ3.js:1:38419)
    at div
    at https://commonwealth.im/assets/index-BHaJreJ3.js:1:37607
    at https://commonwealth.im/assets/index-BHaJreJ3.js:1:38959
    at https://commonwealth.im/assets/index-BHaJreJ3.js:1:3705
    at div
    at div
    at https://commonwealth.im/assets/index-DSouKFnJ.js:1850:11754
    at st (https://commonwealth.im/assets/DiscussionsPage-BPNdRFGZ.js:1:8861)
    at Suspense
    at div
    at div
    at div
    at div
    at Sublayout (https://commonwealth.im/assets/index-DSouKFnJ.js:1858:201527)
    at div
    at X (https://commonwealth.im/assets/index-DSouKFnJ.js:1578:21157)
    at LayoutComponent (https://commonwealth.im/assets/index-DSouKFnJ.js:1858:221641)
    at https://commonwealth.im/assets/index-DSouKFnJ.js:1578:17698
    at RenderedRoute (https://commonwealth.im/assets/index-DSouKFnJ.js:1577:3119)
    at RenderErrorBoundary (https://commonwealth.im/assets/index-DSouKFnJ.js:1577:2292)
    at DataRoutes (https://commonwealth.im/assets/index-DSouKFnJ.js:1578:9054)
    at Router$1 (https://commonwealth.im/assets/index-DSouKFnJ.js:1577:8405)
    at RouterProvider (https://commonwealth.im/assets/index-DSouKFnJ.js:1578:5568)
    at OpenFeatureProvider (https://commonwealth.im/assets/index-DSouKFnJ.js:159:24488)
    at ir (https://commonwealth.im/assets/index-DSouKFnJ.js:1569:91449)
    at QueryClientProvider (https://commonwealth.im/assets/index-DSouKFnJ.js:159:74311)
    at zg (https://commonwealth.im/assets/index-DSouKFnJ.js:1858:214104)
    at App (https://commonwealth.im/assets/index-DSouKFnJ.js:1858:285245)
```

**Comment by Fodenharry** [comment]
> ## Describe the bug
> I've got metamask installed and it says connected to the site. <img alt="image" width="358" src="https://private-user-images.githubusercontent.com/13153687/378213284-b193d2bc-77b1-4a9b-9067-69e710630166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDg3ODIsIm5iZiI6MTcyOTQ0ODQ4MiwicGF0aCI6Ii8xMzE1MzY4Ny8zNzgyMTMyODQtYjE5M2QyYmMtNzdiMS00YTliLTkwNjctNjllNzEwNjMwMTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE4MjEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNmM0YzI2Yjg5ODJiODQzMGY5Y2IyMDJlOWNjYzUyODlkOTM0NWU0MzZkZDlkYmVlZGYyMTVjNWIxMjNjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ImYPVWwLinbiDNCHf3vflMAoUWsayIzyudzrWcX8d7Q">
> 
> Yet it doesn't allow me to login at all. <img alt="image" width="673" src="https://private-user-images.githubusercontent.com/13153687/378213274-3466bfec-716c-411b-bd73-456897fe7ce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDg3ODIsIm5iZiI6MTcyOTQ0ODQ4MiwicGF0aCI6Ii8xMzE1MzY4Ny8zNzgyMTMyNzQtMzQ2NmJmZWMtNzE2Yy00MTFiLWJkNzMtNDU2ODk3ZmU3Y2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE4MjEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMGE5MTA5ZmY0MmVhYzFmZjg3MzQ1NzcyMjQ2MzMxOWU2ZTQyMmJkOGMxYjY2ODQ2NzlmOTAzNGU3NmU0ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gAhrLCvJV1Bqe8132hLbDttv2zy2wGuq7SbizvLZReM">
> 
> ### Initial conditions
> Google chrome
> 
> ## Reproduction steps
> IDK


Hello @drewstone It sounds like you're having a tough time with the login despite MetaMask showing it's connected. Sometimes, even if it says connected, there might be issues with the site itself or the way it's interacting with MetaMask. 

Here are a few things you can try:

1. Refresh the page and try logging in again.
2. Check if your MetaMask is updated to the latest version.
3. Clear your browser cache or try a different browser to see if that helps.
4. Disconnect and reconnect your wallet in MetaMask to refresh the connection.

If none of that works, it might be worth reaching out to the support team for that specific site. They might have more insight into any ongoing issues. Let me know how it goes!

**Comment by dillchen** [comment]
1. Github SSO is now used via Magic, it should be available under another tab.
2. What browser / wallet extensions do u have enabled

**Comment by timolegros** [comment]
Most important question: **are you trying to sign in on a specific community and if so which one?**

Follow-ups: do you have Phantom wallet installed + enabled? Is your MM version up to date? Have you tried with another wallet (Keplr maybe)?
