### ISSUE TITLE
Contest: Console error on contest

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#9729]
## Describe the bug

When Community admin navigate on contest page we have console error

### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

release/v1.7.2-x
**Browser:** 

All
**Wallet:** 

All

## Reproduction steps

1. Go to https://qa.commonwealth.im/shouldselectadifferentaddr/contests
2. Sing in 
3. Navigate on Members & Groups page

## Actual behavior

```
index-HfIymsBy.js:203 Web3ValidatorError: Web3 validator found 1 error[s]:
value at "/0" is required
    at Validator.validate (index-HfIymsBy.js:1700:16546)
    at Web3Validator.validate (index-HfIymsBy.js:1700:18031)
    at Module.utf8ToHex (index-HfIymsBy.js:1700:20223)
    at NamespaceFactory.getNamespaceAddress (index-HfIymsBy.js:1945:31481)
    at NamespaceFactory.getFeeManagerBalance (index-HfIymsBy.js:1945:33928)
    at le (index-ByBpiJcu.js:1:621)
    at Object.queryFn (index-ByBpiJcu.js:1:837)
    at Object._r [as fn] (index-HfIymsBy.js:203:37579)
    at $r (index-HfIymsBy.js:203:32876)
    at index-HfIymsBy.js:203:33297
```
## Expected behavior

We should not have errors

## Screenshots / Video

https://app.screencast.com/Q75WcU1kJRM0x

**Comment by dillchen** [comment]
Is this still showing even after event listener turned on?
